In [1]:
import pandas as pd 
import torch
import torch.nn as nn
import numpy as np
# from AutoODE import LWR_batch_version 
import sys 
sys.path.append("..")
# from DNN import LWRDataset, train_LWR, eval_LWR, test_LWR

# # from AutoODE import LWR_batch_version 
from DNN import Seq2Seq, Seq2Seq_Attn, LWRDataset, LWRDataset_res, train_LWR, eval_LWR, test_LWR, train_hybrid_LWR, eval_hybrid_LWR, test_hybrid_LWR 
from AutoODE import LWR_batch_version, LWR_seq2seq 

In [2]:
import torch 

In [3]:
import os 

os.getcwd() 

'C:\\Users\\Stephen Ma\\Desktop\\AutoODE_PEMS_traffic\\nn\\visualization'

In [4]:
# LWR=torch.load("time_AutoODE1.pt", map_location=torch.device('cpu'))
# seq2seq = torch.load("../result/Seq2Seq/time/best_time_Seq2Seq1.pt", map_location=torch.device('cpu')) 
# LWR=torch.load("../result/LWR/best_space_AutoODE3.pt", map_location=torch.device('cpu')) 
hybridLWR = torch.load("../result/LWR/time_hybridAutoODE1.pt", map_location=torch.device('cpu'))
seq2seq = torch.load("../result/Seq2Seq_Attn/best_time_Seq2Seq_Attn1.pt", map_location=torch.device('cpu')) 

In [19]:
# # hybridLWR = torch.load("../AutoODE_result/time/time_hybridAutoODE2.pt", map_location=torch.device('cpu'))
# hybridLWR = torch.load("../AutoODE_result/space/new_space_hybridAutoODE1.pt", map_location=torch.device('cpu')) 

In [5]:
hybridLWR["preds"].shape 

(10651, 3, 12, 77)

In [21]:
# test_sensors = torch.tensor([3, 11, 13, 14, 15, 16, 19, 24, 27, 29, 31, 36, 38, 41, 50, 62,
#        73, 75, 76]) - 1  
# test_sensors 

In [175]:
hybridLWR["trues"].shape, seq2seq["trues"].shape 

((10651, 3, 12, 77), (10652, 3, 12, 78))

In [176]:
hybridLWR["preds"].shape, hybridLWR["trues"].shape

((10651, 3, 12, 77), (10651, 3, 12, 77))

In [211]:
# seq2seq["trues"][100, 0, 0, 1:4], hybridLWR["trues"][99, 0, 0, test_sensors][:3] # LWR["trues"][111, 0, 0, :3], 
seq2seq["trues"][200, 0, 2, 1:4], hybridLWR["trues"][199, 0, 2, :3]

(array([0.04490819, 0.03767354, 0.03234386], dtype=float32),
 array([0.04490819, 0.03767354, 0.03234386]))

In [133]:
full = np.concatenate((np.expand_dims(seq2seq["trues"][200, :, :, 0], axis=-1), hybridLWR["preds"][199, :, :, :]), axis = 2) 

In [11]:
# np.expand_dims(seq2seq["trues"][100, :, :, 0], axis=-1).shape

In [46]:
full.shape 

(3, 12, 78)

In [13]:
seq2seq["trues"][100, 0, 1, :3], full[0, 1, :3] # LWR["trues"][3, 0, 0, :3], 

(array([0.04420777, 0.03398351, 0.02587413], dtype=float32),
 array([0.04420777, 0.03398351, 0.02587413]))

In [14]:
out["model"].k[0].shape

NameError: name 'out' is not defined

In [ ]:
out["model"].ki[-1].shape

In [6]:
import matplotlib.pyplot as plt

In [ ]:
out["model"].xi.shape

In [7]:
# dx=hybridLWR["model"].dx.cpu().detach().numpy()
# nx=hybridLWR["model"].nx 
dx = 300 
nx = 380 
xpos=np.linspace(0, (nx-1)*dx, nx)

In [8]:
xpos

array([     0.,    300.,    600.,    900.,   1200.,   1500.,   1800.,
         2100.,   2400.,   2700.,   3000.,   3300.,   3600.,   3900.,
         4200.,   4500.,   4800.,   5100.,   5400.,   5700.,   6000.,
         6300.,   6600.,   6900.,   7200.,   7500.,   7800.,   8100.,
         8400.,   8700.,   9000.,   9300.,   9600.,   9900.,  10200.,
        10500.,  10800.,  11100.,  11400.,  11700.,  12000.,  12300.,
        12600.,  12900.,  13200.,  13500.,  13800.,  14100.,  14400.,
        14700.,  15000.,  15300.,  15600.,  15900.,  16200.,  16500.,
        16800.,  17100.,  17400.,  17700.,  18000.,  18300.,  18600.,
        18900.,  19200.,  19500.,  19800.,  20100.,  20400.,  20700.,
        21000.,  21300.,  21600.,  21900.,  22200.,  22500.,  22800.,
        23100.,  23400.,  23700.,  24000.,  24300.,  24600.,  24900.,
        25200.,  25500.,  25800.,  26100.,  26400.,  26700.,  27000.,
        27300.,  27600.,  27900.,  28200.,  28500.,  28800.,  29100.,
        29400.,  297

In [134]:
# xi=hybridLWR["model"].xi.cpu().numpy()
# xi.shape 

# sensor location 

xi = [0,  45,  56,  75,  81,  86,  89,  95, 100, 105, 109, 112, 117,
       124, 128, 133, 137, 141, 146, 149, 152, 158, 163, 167, 171, 174,
       180, 186, 192, 197, 200, 205, 207, 210, 211, 213, 214, 228, 231,
       237, 240, 242, 251, 254, 258, 262, 266, 270, 277, 279, 282, 283,
       286, 288, 291, 294, 296, 298, 300, 303, 308, 310, 315, 317, 320,
       322, 327, 338, 342, 345, 352, 356, 359, 362, 366, 368, 374, 379] 

In [ ]:
LWR["model"].ki[-1].shape 

In [ ]:
xpos[xi].shape # , seq2seq["trues"][1, 0, -1, :].shape 

In [ ]:
#batch id
bi=10 
plt.plot(xpos[xi[0, :]], seq2seq["trues"][1, 0, -1, :], linewidth=0,
        marker="o") 
plt.plot(xpos[xi[0, :]], seq2seq["trues"][1, 0, -1, :]) 

In [ ]:
#batch id
bi=10 
plt.plot(xpos[xi[0, :]], seq2seq["preds"][1, 0, -1, :], linewidth=0,
        marker="o");
plt.plot(xpos[xi[0, :]], seq2seq["preds"][1, 0, -1, :]);

In [ ]:
LWR["model"].k[-1][0,:].max()

In [ ]:
# ksnap=LWR["model"].k[-1][0,:].cpu().detach().numpy()
# usnap=LWR["model"].u[-1][0,:].cpu().detach().numpy()

In [146]:
from scipy.interpolate import interp1d

def interpolate_initial(var, xi, t0=0): 
#     IM_k=interp1d(np.array(xi) * dx, var[0, :], bounds_error=False, 
#                 fill_value=(var[0, 0], var[0, -1]), kind='linear') 
    IM_q=interp1d(np.array(xi) * dx, var[1, :], bounds_error=False, 
                fill_value=(var[1, 0], var[1, -1]), kind='linear') 
    IM_u=interp1d(np.array(xi) * dx, var[2, :], bounds_error=False, 
                fill_value=(var[2, 0], var[2, -1]), kind='linear') 
    
    x=np.linspace(0, (nx-1) * dx, nx) 
    u = IM_u(x)
    q = IM_q(x)
#     k = IM_k(x)
    k = q / u
#     initial = np.stack((k, q, u))
    return k, u

In [177]:
# ksnap, usnap = interpolate_initial(hybridLWR["preds"][199, :, 11, :], xi, t0=0) 
# ksnap, usnap = interpolate_initial(seq2seq["preds"][200, :, 11, :], xi, t0=0) 
# ksnap, usnap = interpolate_initial(seq2seq["trues"][200, :, 11, :], xi, t0=0) 
ksnap, usnap = interpolate_initial(full[:, 11, :], xi, t0=0)

In [178]:
np.save("k_snapshot_LWR.npy", ksnap)
np.save("u_snapshot_LWR.npy", usnap)
np.save("xpos_snapshot_LWR.npy", xpos)

In [179]:
# kisnap=seq2seq["preds"][200, 0, 11, :]
# uisnap=seq2seq["preds"][200, 2, 11, :] 
# kisnap=seq2seq["trues"][200, 0, 11, :]
# uisnap=seq2seq["trues"][200, 2, 11, :] 
# kisnap=hybridLWR["preds"][199, 0, 11, :]
# uisnap=hybridLWR["preds"][199, 2, 11, :] 
kisnap=full[0, 11, :]
uisnap=full[2, 11, :]
np.save("ki_snapshot_LWR.npy", kisnap)
np.save("ui_snapshot_LWR.npy", uisnap)
np.save("xi_snapshot_LWR.npy", xi)